#!/usr/bin/env node
"use strict";

// tools/simulate_revenue_scenarios.js
//
// Simulated customer scenarios for the Strange Works Studio satellite revenue
// lane. Shows the value generated by the first service (Compliance proof
// sprint) and the second service (Compliance template pack) under several
// plausible customer paths.
//
// This script is SIMULATION ONLY. It does not:
//   - touch public-config.js or any review-date or liveMode field,
//   - close any real human-review gate,
//   - generate evidence that should be treated as real,
//   - alter the Operations dashboard hosted-invoice allowlist,
//   - count related-party revenue as market proof.
//
// Every record is flagged simulated: true.

const fs = require("fs");
const path = require("path");

// Mirror of public-config.js services. Kept inline to avoid pulling browser
// globals into a Node script. If the public config changes, update here.
const SERVICES = [
  {
    key: "compliance_proof_sprint",
    publicConfigId: "proof-sprint",
    name: "Compliance proof sprint",
    priceBRL: 750,
    description:
      "Evidence map, checklist cleanup, monthly proof packet, exception notes, and exportable receipt."
  },
  {
    key: "compliance_template_pack",
    publicConfigId: "template-pack",
    name: "Compliance template pack",
    priceBRL: 79,
    description:
      "Checklist templates and renewal worksheets for teams not ready for a managed sprint."
  }
];

// Provider-fee assumptions for simulation only. Real values must come from
// the reviewed payment-provider dashboard and the accountant.
const ASSUMED_PROVIDER_FEE = {
  source: "assumption",
  rate: 0.0499,
  flatBRL: 0.39,
  notes:
    "Placeholder Stripe Brazil hosted-invoice rate for simulation only. Verify with the accountant and the provider dashboard before live launch."
};
const SIMULATION_REVIEW_DATE = "2026-06-12";
const SIMULATION_GOOGLE_FORM_URL = "https://docs.google.com/forms/d/e/simulated/viewform";
const SIMULATION_GOOGLE_SHEET_URL = "https://docs.google.com/spreadsheets/d/simulated";

const SCENARIOS = [
  {
    scenarioId: "S1A",
    serviceKey: "compliance_proof_sprint",
    customerLabel: "Small clinic - Sao Paulo",
    customerType: "business",
    paidDays: 3,
    deliveredDays: 7,
    incidents: 0,
    refund: false,
    notes: "Hosted invoice paid in three business days. No incidents."
  },
  {
    scenarioId: "S1B",
    serviceKey: "compliance_proof_sprint",
    customerLabel: "Mid clinic - Belo Horizonte",
    customerType: "business",
    paidDays: 5,
    deliveredDays: 12,
    incidents: 1,
    refund: false,
    notes:
      "One delivery clarification thread resolved within SUPPORT.md response window."
  },
  {
    scenarioId: "S1C",
    serviceKey: "compliance_proof_sprint",
    customerLabel: "Clinic group - Curitiba",
    customerType: "business",
    paidDays: 4,
    deliveredDays: 10,
    incidents: 0,
    refund: false,
    notes:
      "Customer requested NFS-e ahead of delivery; accountant route closed within timeline."
  },
  {
    scenarioId: "S1D",
    serviceKey: "compliance_proof_sprint",
    customerLabel: "Solo dentist - Recife",
    customerType: "business",
    paidDays: 2,
    deliveredDays: 6,
    incidents: 1,
    refund: true,
    notes:
      "Partial refund issued under TERMOS.md cancellation clause; human refund owner approved."
  },
  {
    scenarioId: "S2A",
    serviceKey: "compliance_template_pack",
    customerLabel: "Solo professional - Porto Alegre",
    customerType: "consumer",
    paidDays: 0,
    deliveredDays: 0,
    incidents: 0,
    refund: false,
    notes: "Same-day hosted invoice and download."
  },
  {
    scenarioId: "S2B",
    serviceKey: "compliance_template_pack",
    customerLabel: "Small clinic - Brasilia",
    customerType: "business",
    paidDays: 1,
    deliveredDays: 1,
    incidents: 0,
    refund: false,
    notes: "Next-day settlement, same-day delivery after settlement."
  },
  {
    scenarioId: "S2C",
    serviceKey: "compliance_template_pack",
    customerLabel: "Solo professional - Salvador",
    customerType: "consumer",
    paidDays: 1,
    deliveredDays: 2,
    incidents: 0,
    refund: false,
    notes: "Pix-style fast settlement simulation."
  },
  {
    scenarioId: "S2D",
    serviceKey: "compliance_template_pack",
    customerLabel: "Solo dentist - Manaus",
    customerType: "consumer",
    paidDays: 1,
    deliveredDays: 1,
    incidents: 1,
    refund: true,
    notes:
      "Refund requested before download; human refund owner approved under TERMOS.md."
  }
];

function round2(n) {
  return Math.round(n * 100) / 100;
}

function serviceForScenario(scenario) {
  const service = SERVICES.find(s => s.key === scenario.serviceKey);
  if (!service) {
    throw new Error(`Unknown serviceKey "${scenario.serviceKey}" in scenario ${scenario.scenarioId}.`);
  }
  return service;
}

function simulateScenario(scenario) {
  const service = serviceForScenario(scenario);
  const gross = service.priceBRL;
  const providerFee = round2(gross * ASSUMED_PROVIDER_FEE.rate + ASSUMED_PROVIDER_FEE.flatBRL);
  const grossAfterRefund = scenario.refund ? round2(gross * 0.5) : gross;
  const netAfterRefund = round2(grossAfterRefund - providerFee);

  const stages = [
    {
      stage: "Draft",
      atDay: 0,
      note: "Order created in private Operations dashboard with non-sensitive scope."
    },
    {
      stage: "Sent",
      atDay: 0,
      note:
        "Hosted invoice link sent from monitored support inbox; URL matches Operations dashboard allowlist."
    },
    {
      stage: "Paid",
      atDay: scenario.paidDays,
      note:
        "Provider or bank settlement confirmed in business account before status change. NFS-e or fiscal receipt issued per accountant route."
    },
    {
      stage: "Delivered",
      atDay: scenario.deliveredDays,
      note:
        "Scoped artifact delivered to access-controlled storage. Acceptance note logged without sensitive data. Receipt chain sealed."
    }
  ];

  if (scenario.refund) {
    stages.push({
      stage: "Refund",
      atDay: scenario.deliveredDays + 2,
      note:
        "Human refund owner approved refund per TERMOS.md. Provider refund recorded; ledger and order updated."
    });
  }

  return {
    simulated: true,
    scenarioId: scenario.scenarioId,
    service: service.name,
    serviceKey: service.key,
    customerLabel: scenario.customerLabel,
    customerType: scenario.customerType,
    grossBRL: round2(gross),
    grossAfterRefundBRL: grossAfterRefund,
    providerFeeBRL: providerFee,
    netBRL: netAfterRefund,
    paidDay: scenario.paidDays,
    deliveredDay: scenario.deliveredDays,
    incidents: scenario.incidents,
    refund: scenario.refund,
    stages,
    notes: scenario.notes
  };
}

function summarize(results) {
  const byService = {};
  for (const result of results) {
    if (!byService[result.service]) {
      byService[result.service] = {
        serviceKey: result.serviceKey,
        scenarioCount: 0,
        grossBRL: 0,
        netBRL: 0,
        refundCount: 0,
        incidentCount: 0
      };
    }
    const bucket = byService[result.service];
    bucket.scenarioCount += 1;
    bucket.grossBRL += result.grossAfterRefundBRL;
    bucket.netBRL += result.netBRL;
    bucket.refundCount += result.refund ? 1 : 0;
    bucket.incidentCount += result.incidents;
  }
  for (const key of Object.keys(byService)) {
    byService[key].grossBRL = round2(byService[key].grossBRL);
    byService[key].netBRL = round2(byService[key].netBRL);
  }
  return byService;
}

function totals(byService) {
  let grossBRL = 0;
  let netBRL = 0;
  let scenarioCount = 0;
  for (const key of Object.keys(byService)) {
    grossBRL += byService[key].grossBRL;
    netBRL += byService[key].netBRL;
    scenarioCount += byService[key].scenarioCount;
  }
  const grossRounded = round2(grossBRL);
  const netRounded = round2(netBRL);
  const marginPct =
    grossRounded > 0 ? round2((netRounded / grossRounded) * 100) : 0;
  return {
    scenarioCount,
    grossBRL: grossRounded,
    netBRL: netRounded,
    marginPct
  };
}

function formatBRL(value) {
  return `R$${value.toFixed(2)}`;
}

function formatReport(results, byService, totalsSummary) {
  const lines = [];
  lines.push("# Revenue Simulation Report");
  lines.push("");
  lines.push(
    "Generated by `tools/simulate_revenue_scenarios.js`. **All data is simulated.** Do not use these IDs, timestamps, or amounts as real evidence. This file is gitignored on purpose."
  );
  lines.push("");
  lines.push("## Assumptions");
  lines.push("");
  lines.push(
    `- Provider fee assumption: ${(ASSUMED_PROVIDER_FEE.rate * 100).toFixed(2)}% + R$${ASSUMED_PROVIDER_FEE.flatBRL.toFixed(2)}.`
  );
  lines.push(`- Notes: ${ASSUMED_PROVIDER_FEE.notes}`);
  lines.push("- Refund scenarios assume a 50% partial refund under TERMOS.md.");
  lines.push("- All customers are simulated external customers. No related-party revenue is counted.");
  lines.push("");
  lines.push("## Per-Service Summary");
  lines.push("");
  lines.push("| Service | Scenarios | Gross | Net | Refunds | Incidents |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const key of Object.keys(byService)) {
    const bucket = byService[key];
    lines.push(
      `| ${key} | ${bucket.scenarioCount} | ${formatBRL(bucket.grossBRL)} | ${formatBRL(bucket.netBRL)} | ${bucket.refundCount} | ${bucket.incidentCount} |`
    );
  }
  lines.push("");
  lines.push("## Totals");
  lines.push("");
  lines.push(`- Scenarios: ${totalsSummary.scenarioCount}`);
  lines.push(`- Gross: ${formatBRL(totalsSummary.grossBRL)}`);
  lines.push(`- Net: ${formatBRL(totalsSummary.netBRL)}`);
  lines.push(`- Margin: ${totalsSummary.marginPct.toFixed(2)}%`);
  lines.push("");
  lines.push("## Scenario Detail");
  lines.push("");
  for (const result of results) {
    lines.push(`### ${result.scenarioId} - ${result.service}`);
    lines.push("");
    lines.push(`- Customer: ${result.customerLabel} (${result.customerType})`);
    lines.push(
      `- Gross: ${formatBRL(result.grossBRL)} | After refund: ${formatBRL(result.grossAfterRefundBRL)} | Provider fee: ${formatBRL(result.providerFeeBRL)} | Net: ${formatBRL(result.netBRL)}`
    );
    lines.push(
      `- Paid day: T+${result.paidDay} | Delivered day: T+${result.deliveredDay} | Incidents: ${result.incidents} | Refund: ${result.refund ? "yes" : "no"}`
    );
    lines.push(`- Notes: ${result.notes}`);
    lines.push("");
    lines.push("| Stage | Day | Note |");
    lines.push("| --- | --- | --- |");
    for (const stage of result.stages) {
      lines.push(`| ${stage.stage} | T+${stage.atDay} | ${stage.note} |`);
    }
    lines.push("");
  }
  lines.push("## What This Does Not Prove");
  lines.push("");
  lines.push(
    "- This report does not close any human-review gate in `HUMAN_REVENUE_INSTRUCTIONS.md`."
  );
  lines.push(
    "- This report does not authorize setting `liveMode: true` in `public-config.js`."
  );
  lines.push(
    "- These customers are simulated. Real-market traction must come from external customers under the closed gates."
  );
  return lines.join("\n") + "\n";
}

function buildSimulatedEvidenceIndex(byService, totalsSummary) {
  return {
    schemaVersion: 1,
    mode: "simulation",
    note:
      "Simulated evidence index produced by tools/simulate_revenue_scenarios.js. This file is gitignored. Do not confuse with REVENUE_SETUP_EVIDENCE_INDEX.local.json or REVENUE_SETUP_EVIDENCE_INDEX.template.json.",
    operator: {
      responsibleOperator: "sim-operator",
      legalBusinessName: "sim-Strange-Works-Studio",
      businessAddressForInvoices: "sim-address-BR",
      supportOwner: "sim-support-owner",
      accountingOwner: "sim-accounting-owner",
      lgpdPrivacyOwner: "sim-privacy-owner",
      paymentReconciliationOwner: "sim-payment-owner",
      refundOwner: "sim-refund-owner",
      dailyInboxCheckTime: "sim-09:00 BRT"
    },
    entity: {
      entityEvidenceId: "sim-entity-001",
      cnpjOrRoute: "sim-cnpj-route",
      reviewerName: "sim-lawyer",
      reviewDate: SIMULATION_REVIEW_DATE,
      allowedToInvoiceServices: true,
      blockers: "simulated-only-not-real-evidence",
      verified: false
    },
    tax: {
      taxEvidenceId: "sim-tax-001",
      taxRegime: "sim-tax-regime",
      cnae: "sim-cnae",
      nfseRoute: "sim-nfse-route",
      municipalRegistrationNeeded: false,
      fiscalDocumentOwner: "sim-fiscal-owner",
      testNfseOrReceiptStatus: "sim-test-receipt-issued",
      accountantReviewedAt: SIMULATION_REVIEW_DATE,
      monthlyReconciliationOwner: "sim-reconciliation-owner",
      verified: false
    },
    payment: {
      paymentEvidenceId: "sim-payment-001",
      provider: "sim-stripe-br",
      businessAccountName: "sim-business-account",
      payoutDestinationVerified: true,
      testPaymentId: "sim-test-pi-001",
      testPayoutStatus: "sim-payout-received",
      refundTestOrProcedure: "sim-refund-test-passed",
      chargebackOrDisputeProcedure: "sim-dispute-procedure-documented",
      feesReviewed: true,
      reconciliationOwner: "sim-reconciliation-owner",
      dashboardAllowlistHostsConfirmed: true,
      verified: false
    },
    support: {
      supportEvidenceId: "sim-support-001",
      supportEmail: "sim-support@example.invalid",
      testSentAt: SIMULATION_REVIEW_DATE,
      testReceivedAt: SIMULATION_REVIEW_DATE,
      dailyCheckTime: "sim-09:00 BRT",
      incidentOwner: "sim-incident-owner",
      refundOwner: "sim-refund-owner",
      privacyOwner: "sim-privacy-owner",
      verified: false
    },
    privacy: {
      privacyEvidenceId: "sim-privacy-001",
      privacyReviewedAt: SIMULATION_REVIEW_DATE,
      lgpdContact: "sim-lgpd-contact",
      processorListLocation: "sim-processor-list",
      retentionDecision: "sim-retention-30d",
      rightsRequestOwner: "sim-rights-owner",
      sensitiveDataBoundaryConfirmed: true,
      verified: false
    },
    terms: {
      termsEvidenceId: "sim-terms-001",
      termsReviewedAt: SIMULATION_REVIEW_DATE,
      reviewer: "sim-lawyer",
      refundPath: "sim-refund-path",
      cancellationPath: "sim-cancellation-path",
      customerType: "consumer-and-business",
      offerScopeConfirmed: true,
      verified: false
    },
    ledger: {
      ledgerEvidenceId: "sim-ledger-001",
      googleFormUrl: SIMULATION_GOOGLE_FORM_URL,
      googleSheetUrl: SIMULATION_GOOGLE_SHEET_URL,
      testSubmissionId: "sim-submission-001",
      tabsVerified: true,
      columnNamesVerified: true,
      allowedStatusValuesVerified: true,
      owner: "sim-ledger-owner",
      verified: false
    },
    publicConfig: {
      operatorName: "Strange Works Studio",
      jurisdiction: "BR",
      supportEmail: "sim-support@example.invalid",
      googleFormUrl: SIMULATION_GOOGLE_FORM_URL,
      supportInboxVerified: false,
      googleFormVerified: false,
      termsReviewedAt: "",
      privacyReviewedAt: "",
      brazilComplianceReviewedAt: "",
      aiHandoffReviewedAt: "",
      liveMode: false
    },
    attestation: {
      operator: "sim-operator",
      reviewedAt: SIMULATION_REVIEW_DATE,
      noSecretsInRepo: true,
      strangeCompanyRemainsSealed: true,
      satelliteIsRevenueOperator: true,
      aiDidNotApproveLegalTaxPaymentOrPrivacy: true
    },
    simulationSummary: {
      perService: byService,
      totals: totalsSummary
    }
  };
}

function printConsoleSummary(byService, totalsSummary) {
  console.log("");
  console.log("=== Revenue Simulation Summary (SIMULATED) ===");
  console.log("");
  for (const key of Object.keys(byService)) {
    const bucket = byService[key];
    console.log(
      `${key}: scenarios=${bucket.scenarioCount} gross=${formatBRL(bucket.grossBRL)} net=${formatBRL(bucket.netBRL)} refunds=${bucket.refundCount} incidents=${bucket.incidentCount}`
    );
  }
  console.log("");
  console.log(
    `Totals: scenarios=${totalsSummary.scenarioCount} gross=${formatBRL(totalsSummary.grossBRL)} net=${formatBRL(totalsSummary.netBRL)} margin=${totalsSummary.marginPct.toFixed(2)}%`
  );
  console.log("");
  console.log("Reminder: this is simulation only. liveMode stays false. No real gate is closed.");
}

function main() {
  const args = process.argv.slice(2);
  const writeReport = args.includes("--write-report");
  const writeEvidence = args.includes("--write-evidence");

  const results = SCENARIOS.map(simulateScenario);
  const byService = summarize(results);
  const totalsSummary = totals(byService);

  if (writeReport) {
    const reportPath = path.join(process.cwd(), "REVENUE_SIMULATION_REPORT.md");
    const reportText = formatReport(results, byService, totalsSummary);
    fs.writeFileSync(reportPath, reportText, "utf8");
    console.log(`Wrote ${path.relative(process.cwd(), reportPath) || reportPath}`);
  }

  if (writeEvidence) {
    const evidencePath = path.join(
      process.cwd(),
      "REVENUE_SETUP_EVIDENCE_INDEX.simulation.json"
    );
    const evidence = buildSimulatedEvidenceIndex(byService, totalsSummary);
    fs.writeFileSync(
      evidencePath,
      JSON.stringify(evidence, null, 2) + "\n",
      "utf8"
    );
    console.log(`Wrote ${path.relative(process.cwd(), evidencePath) || evidencePath}`);
  }

  printConsoleSummary(byService, totalsSummary);
}

if (require.main === module) {
  main();
}

module.exports = {
  SERVICES,
  SCENARIOS,
  ASSUMED_PROVIDER_FEE,
  simulateScenario,
  summarize,
  totals,
  formatReport,
  buildSimulatedEvidenceIndex
};
